### ISSUE TITLE
Uncaught TypeError: this.element.querySelector is not a function

### ISSUE THREAD

**Issue by DUUUDE123** [Kivifreak/linter-processing#4]
[Enter steps to reproduce:]

1. Error occurred when installing linter-processing dependencies

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [linter-processing](https://github.com/Kivifreak/linter-processing) package 2.2.2

### Stack Trace

Uncaught TypeError: this.element.querySelector is not a function

```
At /Users/tylerdalton/.atom/packages/linter-processing/node_modules/atom-package-deps/lib/view.js:41

TypeError: this.element.querySelector is not a function
    at View.advance (/packages/linter-processing/node_modules/atom-package-deps/lib/view.js:41:36)
    at /packages/linter-processing/node_modules/atom-package-deps/lib/main.js:53:16
    at stdout (/packages/linter-processing/node_modules/atom-package-deps/lib/helpers.js:24:11)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:212:17)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -4:37.5.0 snippets:expand (input.hidden-input)
     -4:37.5.0 editor:indent (input.hidden-input)
  4x -4:36.6.0 core:backspace (input.hidden-input)
     -4:17.7.0 core:save (input.hidden-input)
     -3:59 processing:run (input.hidden-input)
     -2:53.2.0 tree-view:move (li.file.entry.list-item.selected)
  5x -2:50 core:backspace (input.hidden-input)
     -2:46.3.0 core:confirm (input.hidden-input)
     -2:33.8.0 processing:run (input.hidden-input)
     -2:14.4.0 core:backspace (input.hidden-input)
     -2:13.3.0 core:save (input.hidden-input)
     -2:06.8.0 settings-view:open (input.hidden-input)
     -1:31.3.0 processing:run (input.hidden-input)
     -1:00.8.0 settings-view:open (input.hidden-input)
     -0:49.5.0 core:cut (input.hidden-input)
     -0:46.5.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
floobits 0.32.12 
linter 2.2.0 
linter-processing 2.2.2 
processing 0.13.0 
project-manager 3.3.5 
```

**Comment by RetroCraft** [comment]
This package appears to be abandoned, I am maintaining a fork/alternative at <https://github.com/AtomLinter/linter-processing-java>

**Comment by bvoq** [comment]
Yes, I'm not maintaining it right now. Do you want me to merge your fork or something?
I can also make you an owner.

**Comment by RetroCraft** [comment]
As I have already migrated my fork to the AtomLinter org, I think it would be best to continue off of that repo. I also have converted the code to Babel...so a merge wouldn't work very well. If you'd like, I can have the guy who migrated my fork (paging @Arcanemagus) to add you to the new repo.
